baseURL: "https://blog.nuvai.cloud"
title: "Luis Sousa Blog"
theme: "hugo-coder"
languageCode: "en"
defaultContentLanguage: "en"
enableEmoji: true
enableRobotsTXT: true

pagination:
  pagerSize: 5

services:
  disqus:
    shortname: "luis-sousa-blog"

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

minify:
  disableXML: true
  minifyOutput: true

params:
  author: "Luis Sousa"
  info: "DevOps & SRE Lead"
  description: "DevOps, Security and random IT things"
  keywords: "Blog,DevOps,SRE,Cloud,Security"
  dateFormat: "January 2, 2006"
  since: 2022
  colorScheme: "auto"
  hideColorSchemeToggle: false

  favicon_32: "/favicon/favicon-32x32.png"
  favicon_16: "/favicon/favicon-16x16.png"
  touchIcon: "/favicon/apple-touch-icon.png"

  social:
    - name: "LinkedIn"
      icon: "fa-brands fa-linkedin fa-2x"
      weight: 1
      url: "https://www.linkedin.com/in/luis-m-sousa/"
    - name: "Bluesky"
      icon: "fa-brands fa-bluesky fa-2x"
      weight: 2
      url: "https://bsky.app/profile/nuvai.cloud"
    - name: "Github"
      icon: "fa-brands fa-github fa-2x"
      weight: 3
      url: "https://github.com/luismsousa"

taxonomies:
  category: "categories"
  series: "series"
  tag: "tags"

menu:
  main:
    - name: "Blog"
      weight: 1
      url: "posts/"
    - name: "About"
      weight: 2
      url: "about/"
    - name: "Tags"
      weight: 3
      url: "tags/"
    - name: "Categories"
      weight: 4
      url: "categories/"
